import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';
import fs from 'fs';
import path from 'path';

const copyToVaultPlugin = {
  name: 'copy-to-vault',
  setup(build) {
    build.onEnd(() => {
      const vaultPluginDir = 'obsidian-test-vault/.obsidian/plugins/task-bridge';
      
      // Ensure directory exists
      if (!fs.existsSync(vaultPluginDir)) {
        fs.mkdirSync(vaultPluginDir, { recursive: true });
      }

      // Copy files to test vault
      if (fs.existsSync('dist/main.js')) {
        fs.copyFileSync('dist/main.js', path.join(vaultPluginDir, 'main.js'));
      }
      if (fs.existsSync('manifest.json')) {
        fs.copyFileSync('manifest.json', path.join(vaultPluginDir, 'manifest.json'));
      }
      if (fs.existsSync('styles.css')) {
        fs.copyFileSync('styles.css', path.join(vaultPluginDir, 'styles.css'));
      }

      console.log(`✅ Plugin files copied to test vault`);
    });
  }
};

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ['src/main.ts'],
  bundle: true,
  external: [
    'obsidian',
    'electron',
    '@codemirror/autocomplete',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/view',
    '@lezer/common',
    '@lezer/highlight',
    '@lezer/lr',
    ...builtinModules],
  format: 'cjs',
  target: 'es2022',
  logLevel: 'info',
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  outfile: 'dist/main.js',
  plugins: [copyToVaultPlugin],
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
