/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ObsidianTaskSyncPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");

// src/utils/logger.ts
var Logger = class {
  namespace;
  constructor(namespace) {
    this.namespace = namespace;
  }
  /**
   * Log an info-level message
   */
  info(message, data) {
    if (data !== void 0) {
      console.info(`[${this.namespace}] ${message}`, data);
    } else {
      console.info(`[${this.namespace}] ${message}`);
    }
  }
  /**
   * Log a warning-level message
   */
  warn(message, data) {
    if (data !== void 0) {
      console.warn(`[${this.namespace}] ${message}`, data);
    } else {
      console.warn(`[${this.namespace}] ${message}`);
    }
  }
  /**
   * Log an error-level message
   */
  error(message, error) {
    if (error !== void 0) {
      console.error(`[${this.namespace}] ${message}`, error);
    } else {
      console.error(`[${this.namespace}] ${message}`);
    }
  }
  /**
   * Log a debug-level message
   */
  debug(message, data) {
    if (process.env.DEBUG) {
      if (data !== void 0) {
        console.debug(`[${this.namespace}] ${message}`, data);
      } else {
        console.debug(`[${this.namespace}] ${message}`);
      }
    }
  }
};

// src/main.ts
var logger = new Logger("ObsidianTaskSync");
var ObsidianTaskSyncPlugin = class extends import_obsidian.Plugin {
  async onload() {
    try {
      logger.info("Obsidian Task Sync plugin loaded");
    } catch (error) {
      const userMessage = "Failed to load Obsidian Task Sync plugin. Check console for details or contact the author with the console output.";
      logger.error("Plugin load failed", error);
      new import_obsidian.Notice(userMessage);
    }
  }
  async onunload() {
    logger.info("Obsidian Task Sync plugin unloaded");
  }
};
