/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);
var __async = (__this, __arguments, generator) => {
  return new Promise((resolve, reject) => {
    var fulfilled = (value) => {
      try {
        step(generator.next(value));
      } catch (e) {
        reject(e);
      }
    };
    var rejected = (value) => {
      try {
        step(generator.throw(value));
      } catch (e) {
        reject(e);
      }
    };
    var step = (x) => x.done ? resolve(x.value) : Promise.resolve(x.value).then(fulfilled, rejected);
    step((generator = generator.apply(__this, __arguments)).next());
  });
};

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ObsidianTicktickSyncPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");

// src/utils/logger.ts
var Logger = class {
  constructor(namespace) {
    this.namespace = namespace;
  }
  /**
   * Log an info-level message
   */
  info(message, data) {
    console.info(`[${this.namespace}] ${message}`, data);
  }
  /**
   * Log a warning-level message
   */
  warn(message, data) {
    console.warn(`[${this.namespace}] ${message}`, data);
  }
  /**
   * Log an error-level message
   */
  error(message, error) {
    console.error(`[${this.namespace}] ${message}`, error);
  }
  /**
   * Log a debug-level message
   */
  debug(message, data) {
    if (process.env.DEBUG) {
      console.debug(`[${this.namespace}] ${message}`, data);
    }
  }
};

// src/main.ts
var logger = new Logger("ObsidianTicktickSync");
var ObsidianTicktickSyncPlugin = class extends import_obsidian.Plugin {
  onload() {
    return __async(this, null, function* () {
      try {
        logger.info("Obsidian Ticktick Sync plugin loaded");
      } catch (error) {
        const userMessage = "Failed to load Obsidian Ticktick Sync plugin. Check console for details.";
        logger.error("Plugin load failed", error);
        new import_obsidian.Notice(userMessage);
      }
    });
  }
  onunload() {
    return __async(this, null, function* () {
      logger.info("Obsidian Ticktick Sync plugin unloaded");
    });
  }
};
